USE [master]
GO

/****** Object:  Database [academic2]    Script Date: 24/07/2015 23:36:13 ******/
IF (EXISTS (select * from sys.databases where name = 'academic2'))
BEGIN
    DROP DATABASE [academic2]
END
GO

/****** Object:  Database [academic2]    Script Date: 24/07/2015 23:36:13 ******/
CREATE DATABASE [academic2]
 CONTAINMENT = NONE
GO

ALTER DATABASE [academic2] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [academic2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [academic2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [academic2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [academic2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [academic2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [academic2] SET ARITHABORT OFF 
GO

ALTER DATABASE [academic2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [academic2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [academic2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [academic2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [academic2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [academic2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [academic2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [academic2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [academic2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [academic2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [academic2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [academic2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [academic2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [academic2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [academic2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [academic2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [academic2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [academic2] SET RECOVERY FULL 
GO

ALTER DATABASE [academic2] SET  MULTI_USER 
GO

ALTER DATABASE [academic2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [academic2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [academic2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [academic2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [academic2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [academic2] SET  READ_WRITE 
GO


